name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the Nuxt.js app
        run: npm run build

      - name: Deploy to Hosting Service
        run: |
          # Comando para implantar seu site no serviço de hospedagem, como Netlify ou Vercel.
          # Certifique-se de configurar as credenciais apropriadas no ambiente.
      
      - name: Lint with ESLint
        run: npm run lint

      - name: Format with Prettier
        run: npm run format

env:
  CI: true
