name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      
      - name: Lint with ESLint
        run: npm run lint

      - name: Format with Prettier
        run: npm run format

     - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "Daniel.Bolotaro"
          git config --global user.email "danielbolotaro@edu.unifil.br"
          git config --global credential.helper store
          echo "https://GHA_TOKEN@github.com" > ~/.git-credentials
        env:
          GHA_TOKEN: ${{ secrets.GHA_TOKEN }}


env:
  CI: true
